services:
  spring-boot:
    build:
      context: .
      dockerfile: Dockerfile
    image: choihorim/flowify-backend:latest
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MONGODB_URL: ${MONGODB_URL}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173}
      FASTAPI_URL: ${FASTAPI_URL:-http://host.docker.internal:8000}
      SERVER_PORT: ${SERVER_PORT:-8080}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      ENCRYPTION_SECRET_KEY: ${ENCRYPTION_SECRET_KEY}
      INTERNAL_API_SECRET: ${INTERNAL_API_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:-http://localhost:8080/api/auth/google/callback}
      FRONT_REDIRECT_URI: ${FRONT_REDIRECT_URI:-http://localhost:5173/auth/callback}
      SLACK_CLIENT_ID: "${SLACK_CLIENT_ID}"
      SLACK_CLIENT_SECRET: "${SLACK_CLIENT_SECRET}"
      SLACK_REDIRECT_URI: "${SLACK_REDIRECT_URI:-http://localhost:8080/api/oauth-tokens/slack/callback}"
